# Generated by Django 5.1.4 on 2025-01-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_managers_remove_user_full_name_user_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(default=None, max_length=32, unique=True, verbose_name='OTP Secret'),
        ),
    ]
