# Generated by Django 5.1.4 on 2025-01-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True, verbose_name='OTP Secret'),
        ),
    ]
