# Generated by Django 5.1.4 on 2025-01-05 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViabilidadeEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_interesse', models.CharField(max_length=100)),
                ('is_matriz', models.BooleanField(verbose_name='É matriz?')),
                ('is_filial', models.BooleanField(verbose_name='É filial?')),
                ('inscricao_imobiliaria', models.CharField(max_length=50)),
                ('area_estabelecimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inscricao_estadual', models.BooleanField(verbose_name='Solicita Inscrição Estadual?')),
                ('tipo_juridico', models.CharField(choices=[('EMP', 'Empresário'), ('SOC', 'Sociedade Empresária'), ('MEI', 'MEI'), ('SA', 'Sociedade Anônima'), ('COOP', 'Cooperativa'), ('CONS', 'Consórcio'), ('SOC_SIMP', 'Sociedade')], max_length=10)),
                ('natureza_juridica', models.CharField(choices=[('LTDA', 'Sociedade empresária Ltda'), ('COL', 'Sociedade Empresária em nome coletivo'), ('CS', 'Sociedade Empresária em Comandita Simples'), ('CA', 'Sociedade Empresária em Comandita por Ações'), ('GS', 'Grupo de Sociedades'), ('SE', 'Estabelecimento, no Brasil, de Sociedade Estrangeira'), ('BIN', 'Estabelecimento, no Brasil, de empresa Binacional Argentino-Brasileira')], max_length=10)),
                ('tipo_unidade', models.CharField(choices=[('PROD', 'Unidade Produtiva'), ('SEDE', 'Sede'), ('ESC', 'Escritório Administrativo'), ('DEP', 'Depósito Fechado'), ('ALM', 'Almoxarifado'), ('OFC', 'Oficina de Reparação'), ('GAR', 'Garagem'), ('COMB', 'Unidade de abastecimento de combustíveis'), ('EXP', 'Ponto de exposição'), ('TREI', 'Centro de treinamento'), ('CPD', 'Centro de Processamento de Dados'), ('COL', 'Posto de Coleta')], max_length=10)),
                ('forma_atuacao', models.CharField(choices=[('FIXO', 'Estabelecimento Fixo'), ('INT', 'Internet'), ('FORA', 'Em Local Fixo Fora de Loja'), ('CORREIO', 'Correio'), ('PORTA', 'Porta a Porta, Postos Móveis ou por Ambulantes'), ('TELE', 'Televendas'), ('AUTO', 'Máquinas Automáticas'), ('EXT', 'Atividade Desenvolvida Fora do Estabelecimento')], max_length=10)),
                ('cep', models.CharField(max_length=8)),
                ('uf', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('tipo_logradouro', models.CharField(max_length=50)),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('ponto_referencia', models.TextField(blank=True)),
                ('nome_empresarial', models.CharField(max_length=200)),
                ('usar_cnpj_nome', models.BooleanField(default=False)),
                ('objeto_social', models.TextField()),
                ('cnae_principal', models.CharField(max_length=7)),
                ('cnaes_secundarios', models.TextField(blank=True)),
                ('enquadramento', models.CharField(choices=[('EPP', 'EPP - Empresa de Pequeno Porte'), ('ME', 'ME - Micro-empresa'), ('NORMAL', 'Normal ou outros enquadramentos')], max_length=10)),
                ('area_construida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tem_habite_se', models.BooleanField(verbose_name='Possui Habite-se?')),
                ('optante_simples', models.BooleanField(verbose_name='Optante pelo Simples Nacional?')),
                ('telefone_contato', models.CharField(max_length=20)),
                ('nome_contador', models.CharField(max_length=200)),
                ('registro_bombeiros', models.CharField(blank=True, max_length=50)),
                ('capital_social', models.DecimalField(decimal_places=2, max_digits=15)),
                ('qtd_quotas', models.IntegerField()),
                ('valor_quota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_capital', models.CharField(choices=[('ESP', 'ESPÉCIE'), ('IMO', 'IMÓVEIS'), ('OUT', 'OUTROS')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('is_administrador', models.BooleanField(verbose_name='É administrador?')),
                ('endereco', models.TextField()),
                ('qtd_quotas', models.IntegerField()),
                ('viabilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CNPJManager.viabilidadeempresa')),
            ],
        ),
    ]
